### ISSUE TITLE
Cannot get my ticket for Flutter Europe

### ISSUE THREAD

**Issue by annalaufey** [eventil/eventil.com#229] opened 2019-10-14 16:17 UTC
I just bought a ticket for Flutter Europe without being logged in. I never received my ticket or invoice trough emailI. I have a screen shot of the invoice, but I don't have a ticket.

I was going to try to sign up for an account, but I guess eventil created an account for me automatically when I bought it?

Now I can't log in and trying to reset my password on eventil.com/forgot/new doesn't work. I never receive an email to reset my password and am therefor stuck. 

I already sent an email to hello@eventil.com with further information. Can you please help me so I can access my ticket.

**Comment by zaiste** [comment] 2019-11-06 12:24
The issue is resolved. The emails have been sent and marked as delivered in our systems. This might have been related to an issue with a firewall on the user site.

**Closed as completed by zaiste** 2019-11-06 12:24 UTC
